services:
  backend: 
          build: ./backend
          environment:
                  FLASK_ENV: development
          command: ["flask", "run"]
          volumes:
                  - ./backend:/backend
          stop_signal: SIGINT
          network_mode: host
          ports:
                  - '5000:5000'
  frontend:
          build: ./frontend
          command: ["npm", "run", "dev"]
          volumes:
                  - ./frontend:/frontend
          stop_signal: SIGINT
          network_mode: host
          ports:
                  - '8080:8080'
